export default {
  "_version": 4,
  "_name": "English",
  "flag": {
    /**
     * The country names listed below is how osu! spells them.
     */
    "__": "",

    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla",
    "AL": "Albania",
    "AM": "Armenia",
    "AN": "Netherlands Antilles",
    "AO": "Angola",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Aland Islands",
    "AZ": "Azerbaijan",

    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint Barthelemy",
    "BM": "Bermuda",
    "BN": "Brunei",
    "BO": "Bolivia",
    "BR": "Brazil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",

    "CA": "Canada",
    "CD": "Congo, The Democratic Republic of the",
    "CF": "Central African Republic",
    "CG": "Congo",
    "CH": "Switzerland",
    "CI": "Cote D'Ivoire",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CX": "Christmas Island",
    "CY": "Cyprus",
    "CZ": "Czech Republic",

    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",

    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "EU": "Europe",

    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Islands (Malvinas)",
    "FM": "Micronesia, Federated States of",
    "FO": "Faroe Islands",
    "FR": "France",

    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "Georgia",
    "GF": "French Guiana",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "Gambia",
    "GN": "Guinea",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",

    "HK": "Hong Kong",
    "HM": "Heard Island and McDonald Islands",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",

    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IM": "Isle of Man",
    "IN": "India",
    "IQ": "Iraq",
    "IR": "Iran, Islamic Republic of",
    "IS": "Iceland",
    "IT": "Italy",

    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",

    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comoros",
    "KN": "Saint Kitts and Nevis",
    "KP": "Korea, Democratic People's Republic of",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",

    "LA": "Lao People's Democratic Republic",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",

    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Moldova",
    "ME": "Montenegro",
    "MF": "Saint Martin",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MK": "North Macedonia",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolia",
    "MO": "Macau",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",

    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "New Zealand",

    "OM": "Oman",

    "PA": "Panama",
    "PE": "Peru",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "Saint Pierre and Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PS": "Palestinian Territory Occupied",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",

    "QA": "Qatar",

    "RE": "Reunion",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russian Federation",
    "RW": "Rwanda",

    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SH": "Saint Helena",
    "SI": "Slovenia",
    "SJ": "Svalbard and Jan Mayen",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Suriname",
    "ST": "Sao Tome and Principe",
    "SV": "El Salvador",
    "SY": "Syrian Arab Republic",
    "SZ": "Eswatini",

    "TC": "Turks and Caicos Islands",
    "TD": "Chad",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TR": "Turkey",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan",
    "TZ": "Tanzania, United Republic of",

    "UA": "Ukraine",
    "UG": "Uganda",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",

    "VA": "Holy See (Vatican City State)",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "VN": "Vietnam",
    "VU": "Vanuatu",

    "WS": "Samoa",

    "YE": "Yemen",
    "YT": "Mayotte",

    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
  },
  "interface": {
    "close": "Close",
    "copy": "Copy",
    "copied": "Copied",
    "failed": "Failed",
    "help": "Help",
    "help1": "Copy and paste your markdown into the text box (or drag-and-drop).",
    "help2": "Click \"Find Flags\".",
    "help3": "Copy and paste the results into your markdown file.",
    "feedback": "Issues or Feedback",
    "example": "Example",
    "config": "Settings",
    "config-name": "Set country name in title (hover text)",
    "config-code": "Set country code in alt (image failed to load text)",
    "config-parsefix": "Try to apply fixes right away",
    "config-inout": "Include input with output",
    "config-lang": "Interface and output lanauage:",
    "output-has-errors": "Some issues were found.",
    "output-has-fixes": "Some modifications were made.",
    "show-errors": "Show Issues",
    "parse": "Find Flags",
    "errors": "Issues",
    "use-instead": "use instead:",
    "line": "line"
  },
  "example": "---\ntags:\n  - FWO20XX\n---\n\n# flag-wiki-osu 20XX\n\n![FWO20XX Logo](img/logo.png)\n\nThe **flag-wiki-osu** (***FWO20XX***) was a country-based double-elimination osu! tournament hosted by ![Austrila][flag_AU] [peppy] https://osu.ppy.sh/users/2), ![](/wiki/shared/flag/DE.gif \"Germany\") [Loctav](https://osu.ppy.sh/users/71366), and ![NZ][flag_NZ] [deadbeat](https://osu.ppy.sh/users/128370). It was the first installment of the flag-wiki-osu.\n\n## Schedule\n\n| Event | Timestamp |\n| --: | :-- |\n| Registration Phase | 2018-01-01/2018-01-28 |\n| Live Drawings | 2018-01-29 (12:00 UTC) |\n\n## Prizes\n\n| Placing | Prize(s) |\n| :-: | :-- |\n| ![Gold Crown](/wiki/shared/GCrown.png \"1st place\") | ![](/wiki/shared/flag/AR.gif) [juankristal](https://osu.ppy.sh/users/43656) |\n| ![Silver Crown](/wiki/shared/SCrown.png \"2nd place\") | ![][flag_US] [ztrot](https://osu.ppy.sh/users/6347) |\n| ![Bronze Crown](/wiki/shared/BCrown.png \"3rd place\") | ![DE][flag_DE] [Nwolf](https://osu.ppy.sh/users/1910766) |\n\n## Organisation\n\nThe flag-wiki-osu is run by various community members by distributing the multitude of tasks into various fields of responsibility.\n\n| Position | Member(s) |\n| :-- | :-- |\n| Manager | ![][flag_US] [clayton](https://osu.ppy.sh/users/3666350) |\n| Map Selector | ![][flag_CN] [kj415j45](https://osu.ppy.sh/users/9367540) |\n| Statistician | ![US][flag_US] [Joehu](https://osu.ppy.sh/users/8549835) |\n\n## Random People\n\n|  | Country | Members |\n| :-: | :-: | :-- |\n| ![][flag_AU] | **Australia** | [peppy](https://osu.ppy.sh/users/2), [BanchoBot](https://osu.ppy.sh/users/3) |\n| ![][flag_US] | **United States** | [Toy](https://osu.ppy.sh/users/2757689), [Apraxia](https://osu.ppy.sh/users/4194445) |\n\n"
};
