export default {
  "_version": 4,
  "_name": "Brazilian Portuguese (output only)",
  "flag": {
    "__": "",

    "AD": "Andorra",
    "AE": "Emirados Árabes Unidos",
    "AF": "Afganistão",
    "AG": "Antígua e Barbuda",
    "AI": "Anguilla",
    "AL": "Albânia",
    "AM": "Arménia",
    "AN": "Antilhas Neerlandesas",
    "AO": "Angola",
    "AR": "Argentina",
    "AS": "Samoa Americana",
    "AT": "Áustria",
    "AU": "Austrália",
    "AW": "Aruba",
    "AX": "Ilhas de Aland",
    "AZ": "Azerbaijão",

    "BA": "Bósnia e Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Bélgica",
    "BF": "Burkina Faso",
    "BG": "Bulgária",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benim",
    "BL": "São Bartolomeu",
    "BM": "Bermudas",
    "BN": "Brunei",
    "BO": "Bolívia",
    "BR": "Brasil",
    "BS": "Bahamas",
    "BT": "Butão",
    "BW": "Botswana",
    "BY": "Bielorrússia",
    "BZ": "Belize",

    "CA": "Canadá",
    "CD": "Congo, República Democrática do",
    "CF": "República Centro-Africana",
    "CG": "Congo",
    "CH": "Suíça",
    "CI": "Costa do Marfim",
    "CL": "Chile",
    "CM": "Camarões",
    "CN": "China",
    "CO": "Colômbia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CX": "Ilha de Páscoa",
    "CY": "Chipre",
    "CZ": "República Checa",

    "DE": "Alemanha",
    "DJ": "Djibouti",
    "DK": "Dinamarca",
    "DM": "Dominica",
    "DO": "República Dominicana",
    "DZ": "Algeria",

    "EC": "Equador",
    "EE": "Estônia",
    "EG": "Egito",
    "ER": "Eritrea",
    "ES": "Espanha",
    "ET": "Etiópia",
    "EU": "Europa",

    "FI": "Finlândia",
    "FJ": "Fiji",
    "FK": "Ilhas Malvinas",
    "FM": "Micronésia, Estados Federados da",
    "FO": "Ilhas Faroé",
    "FR": "França",

    "GA": "Gabão",
    "GB": "Reino Unido",
    "GD": "Granada",
    "GE": "Geórgia",
    "GF": "Guiana Francesa",
    "GG": "Guernsey",
    "GH": "Gana",
    "GI": "Gibraltar",
    "GL": "Groenlândia",
    "GM": "Gâmbia",
    "GN": "Guiné",
    "GP": "Guadalupe",
    "GQ": "Guiné Equatorial",
    "GR": "Grécia",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guiné-Bissau",
    "GY": "Guiana",

    "HK": "Hong Kong",
    "HM": "Ilha Heard e Ilhas McDonald",
    "HN": "Honduras",
    "HR": "Croácia",
    "HT": "Haiti",
    "HU": "Hungria",

    "ID": "Indonésia",
    "IE": "Irlanda",
    "IL": "Israel",
    "IM": "Ilha de Man",
    "IN": "Índia",
    "IQ": "Iraque",
    "IR": "Irã, República Islâmica do",
    "IS": "Islândia",
    "IT": "Itália",

    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordânia",
    "JP": "Japão",

    "KE": "Quênia",
    "KG": "Quirguistão",
    "KH": "Camboja",
    "KI": "Quiribati",
    "KM": "Comores",
    "KN": "São Cristóvão e Névis",
    "KP": "Coreia, República Popular Democrática da",
    "KR": "Coreia do Sul",
    "KW": "Kuwait",
    "KY": "Ilhas Cayman",
    "KZ": "Cazaquistão",

    "LA": "Laos",
    "LB": "Líbano",
    "LC": "Santa Lúcia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Libéria",
    "LS": "Lesoto",
    "LT": "Lituânia",
    "LU": "Luxemburgo",
    "LV": "Letônia",
    "LY": "Líbia",

    "MA": "Marrocos",
    "MC": "Mônaco",
    "MD": "Moldávia",
    "ME": "Montenegro",
    "MF": "São Martinho",
    "MG": "Madagascar",
    "MH": "Ilhas Marshall",
    "MK": "Macedônia do Norte",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongólia",
    "MO": "Macau",
    "MP": "Ilhas Marianas do Norte",
    "MQ": "Martinica",
    "MR": "Mauritânia",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Maurícia",
    "MV": "Maldivas",
    "MW": "Malawi",
    "MX": "México",
    "MY": "Malásia",
    "MZ": "Moçambique",

    "NA": "Namíbia",
    "NC": "Nova Caledônia",
    "NE": "Níger",
    "NF": "Ilha Norfolk",
    "NG": "Nigéria",
    "NI": "Nicarágua",
    "NL": "Netherlands",
    "NO": "Noruega",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "Nova Zelândia",

    "OM": "Omã",

    "PA": "Panamá",
    "PE": "Peru",
    "PF": "Polinésia Francesa",
    "PG": "Papua-Nova Guiné",
    "PH": "Filipinas",
    "PK": "Paquistão",
    "PL": "Polônia",
    "PM": "Saint Pierre e Miquelon",
    "PN": "Picárnia",
    "PR": "Porto Rico",
    "PS": "Territórios Palestinos",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguai",

    "QA": "Qatar",

    "RE": "Reunião",
    "RO": "Romênia",
    "RS": "Sérvia",
    "RU": "Federação Russa",
    "RW": "Ruanda",

    "SA": "Arábia Saudita",
    "SB": "Ilhas Salomão",
    "SC": "Seychelles",
    "SD": "Sudão",
    "SE": "Suécia",
    "SG": "Singapura",
    "SH": "Santa Helena",
    "SI": "Eslovênia",
    "SJ": "Svalbard e Jan Mayen",
    "SK": "Eslováquia",
    "SL": "Serra Leoa",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somália",
    "SR": "Suriname",
    "ST": "São Tomé e Príncipe",
    "SV": "El Salvador",
    "SY": "República Árabe Síria",
    "SZ": "Suazilândia",

    "TC": "Ilhas Turcas e Caicos",
    "TD": "Chade",
    "TG": "Togo",
    "TH": "Tailândia",
    "TJ": "Tajiquistão",
    "TL": "Timor-Leste",
    "TM": "Turcomenistão",
    "TN": "Tunísia",
    "TO": "Tonga",
    "TR": "Turquia",
    "TT": "Trinidade e Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan",
    "TZ": "Tanzânia, República Unida da",

    "UA": "Ucrânia",
    "UG": "Uganda",
    "US": "Estados Unidos",
    "UY": "Uruguai",
    "UZ": "Uzbequistão",

    "VA": "Vaticano (Estado da Cidade do Vaticano)",
    "VC": "São Vicente e Granadinas",
    "VE": "Venezuela",
    "VG": "Ilhas Virgens Britânicas",
    "VI": "Ilhas Virgens Americanas",
    "VN": "Vietnã",
    "VU": "Vanuatu",

    "WS": "Samoa",

    "YE": "Iêmen",
    "YT": "Mayotte",

    "ZA": "África do Sul",
    "ZM": "Zâmbia",
    "ZW": "Zimbábue",
  },
};
