export default {
  "_version": 4,
  "_name": "Turkish (output only)",
  "flag": {
    "__": "",

    "AD": "Andorra",
    "AE": "Birleşik Arap Emirlikleri",
    "AF": "Afganistan",
    "AG": "Antigua ve Barbuda",
    "AI": "Anguilla",
    "AL": "Arnavutluk",
    "AM": "Ermenistan",
    "AN": "Hollanda Antilleri",
    "AO": "Angola",
    "AR": "Arjantin",
    "AS": "Amerikan Samoası",
    "AT": "Avusturya",
    "AU": "Avustralya",
    "AW": "Aruba",
    "AX": "Aland Adaları",
    "AZ": "Azerbaycan",

    "BA": "Bosnia Hersek",
    "BB": "Barbados",
    "BD": "Bangladeş",
    "BE": "Belçika",
    "BF": "Burkina Faso",
    "BG": "Bulgaristan",
    "BH": "Bahreyn",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint Barthelemy",
    "BM": "Bermuda",
    "BN": "Brunei",
    "BO": "Bolivya",
    "BR": "Brezilya",
    "BS": "Bahamalar",
    "BT": "Bhutan",
    "BW": "Botsvana",
    "BY": "Belarus",
    "BZ": "Belize",

    "CA": "Kanada",
    "CD": "Kongo Demokratik Cumhuriyeti",
    "CF": "Orta Afrika Cumhuriyeti",
    "CG": "Kongo",
    "CH": "İsviçre",
    "CI": "Fildişi Sahili",
    "CL": "Şili",
    "CM": "Kamerun",
    "CN": "Çin",
    "CO": "Kolombiya",
    "CR": "Kosta Rika",
    "CU": "Küba",
    "CV": "Yeşil Burun Adaları",
    "CX": "Christmas Adası",
    "CY": "Kıbrıs Cumhuriyeti",
    "CZ": "Çek Cumhuriyeti",

    "DE": "Almanya",
    "DJ": "Cibuti",
    "DK": "Danimarka",
    "DM": "Dominika",
    "DO": "Dominik Cumhuriyeti",
    "DZ": "Cezayir",

    "EC": "Ekvador",
    "EE": "Estonya",
    "EG": "Mısır",
    "ER": "Eritre",
    "ES": "İspanya",
    "ET": "Etiyopya",
    "EU": "Avrupa",

    "FI": "Finlandiya",
    "FJ": "Fiji",
    "FK": "Falkland Adaları (Malvinalar)",
    "FM": "Mikronezya Federal Devletleri",
    "FO": "Faroe Adaları",
    "FR": "Fransa",

    "GA": "Gabon",
    "GB": "Birleşik Krallık",
    "GD": "Grenada",
    "GE": "Gürcistan",
    "GF": "Fransız Guyanası",
    "GG": "Guernsey",
    "GH": "Gana",
    "GI": "Cebelitarık",
    "GL": "Grönland",
    "GM": "Gambiya",
    "GN": "Gine",
    "GP": "Guadeloupe",
    "GQ": "Ekvatoral Gine",
    "GR": "Yunanistan",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Gine-Bissau",
    "GY": "Guyana",

    "HK": "Hong Kong",
    "HM": "Heard Adası ve McDonald Adaları",
    "HN": "Honduras",
    "HR": "Hırvatistan",
    "HT": "Haiti",
    "HU": "Macaristan",

    "ID": "Endonezya",
    "IE": "İrlanda",
    "IL": "İsrail",
    "IM": "Man Adası",
    "IN": "Hindistan",
    "IQ": "Irak",
    "IR": "İran İslam Cumhuriyeti",
    "IS": "İzlanda",
    "IT": "İtalya",

    "JE": "Jersey",
    "JM": "Jamaika",
    "JO": "Ürdün",
    "JP": "Japonya",

    "KE": "Kenya",
    "KG": "Kırgızistan",
    "KH": "Kamboçya",
    "KI": "Kiribati",
    "KM": "Komorlar",
    "KN": "Saint Kitts ve Nevis",
    "KP": "Kore Demokratik Halk Cumhuriyeti",
    "KR": "Güney Kore",
    "KW": "Kuveyt",
    "KY": "Cayman Adaları",
    "KZ": "Kazakistan",

    "LA": "Lao Demokratik Halk Cumhuriyeti",
    "LB": "Lübnan",
    "LC": "Saint Lucia",
    "LI": "Lihtenştayn",
    "LK": "Sri Lanka",
    "LR": "Liberya",
    "LS": "Lesotho",
    "LT": "Litvanya",
    "LU": "Lüksemburg",
    "LV": "Letonya",
    "LY": "Libya",

    "MA": "Fas",
    "MC": "Monako",
    "MD": "Moldova",
    "ME": "Montenegro",
    "MF": "Saint Martin",
    "MG": "Madagaskar",
    "MH": "Marshall Adaları",
    "MK": "Kuzey Makedonya",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Moğolistan",
    "MO": "Makao",
    "MP": "Kuzey Mariana Adaları",
    "MQ": "Martinik",
    "MR": "Moritanya",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldivler",
    "MW": "Malavi",
    "MX": "Meksika",
    "MY": "Malezya",
    "MZ": "Mozambik",

    "NA": "Namibya",
    "NC": "Yeni Kaledonya",
    "NE": "Nijer",
    "NF": "Norfolk Adaları",
    "NG": "Nijerya",
    "NI": "Nikaragua",
    "NL": "Hollanda",
    "NO": "Norveç",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "Yeni Zelanda",

    "OM": "Oman",

    "PA": "Panama",
    "PE": "Peru",
    "PF": "Fransız Polynezyası",
    "PG": "Papua Yeni Gine",
    "PH": "Filipinler",
    "PK": "Pakistan",
    "PL": "Polonya",
    "PM": "Saint Pierre ve Miquelon",
    "PN": "Pitcairn",
    "PR": "Porto Riko",
    "PS": "Filistin",
    "PT": "Portekiz",
    "PW": "Palau",
    "PY": "Paraguay",

    "QA": "Katar",

    "RE": "Reunion",
    "RO": "Romanya",
    "RS": "Sırbistan",
    "RU": "Rusya Federasyonu",
    "RW": "Ruanda",

    "SA": "Suudi Arabistan",
    "SB": "Solomon Adaları",
    "SC": "Seyşeller",
    "SD": "Sudan",
    "SE": "İsveç",
    "SG": "Singapur",
    "SH": "Saint Helena",
    "SI": "Slovenya",
    "SJ": "Svalbard ve Jan Mayen",
    "SK": "Slovakya",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somali",
    "SR": "Surinam",
    "ST": "Sao Tome ve Principe",
    "SV": "El Salvador",
    "SY": "Suriye Arap Cumhuriyeti",
    "SZ": "Esvatini",

    "TC": "Turks ve Caicos Adaları",
    "TD": "Çad",
    "TG": "Togo",
    "TH": "Tayland",
    "TJ": "Tacikistan",
    "TL": "Timor-Leste",
    "TM": "Türkmenistan",
    "TN": "Tunus",
    "TO": "Tonga",
    "TR": "Türkiye",
    "TT": "Trinidad ve Tobago",
    "TV": "Tuvalu",
    "TW": "Tayvan",
    "TZ": "Tanzanya Birleşik Cumhuriyeti",

    "UA": "Ukrayna",
    "UG": "Uganda",
    "US": "Birleşik Devletler",
    "UY": "Uruguay",
    "UZ": "Özbekistan",

    "VA": "Kutsal Makam (Vatikan Şehir Devleti)",
    "VC": "Saint Vincent ve Grenadinler",
    "VE": "Venezuela",
    "VG": "Britanya Virjin Adaları",
    "VI": "A.B.D. Virjin Adaları",
    "VN": "Vietnam",
    "VU": "Vanuatu",

    "WS": "Samoa",

    "YE": "Yemen",
    "YT": "Mayotte",

    "ZA": "Güney Afrika",
    "ZM": "Zambiya",
    "ZW": "Zimbabve"
  },
};
