export default Object.freeze({
  "_version": 1,
  "_name": "English",
  "flag": {
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla",
    "AL": "Albania",
    "AM": "Armenia",
    "AN": "Netherlands Antilles",
    "AO": "Angola",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Åland Islands",
    "AZ": "Azerbaijan",

    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint Barthélemy",
    "BM": "Bermuda",
    "BN": "Brunei Darussalam",
    "BO": "Bolivia", // "BO": "Plurinational State of Bolivia",
    // "BQ": "Bonaire, Sint Eustatius and Saba",
    "BR": "Brazil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    // "BV": "Bouvet Island",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",

    "CA": "Canada",
    // "CC": "Cocos (Keeling) Islands",
    "CD": "Democratic Republic of the Congo",
    "CF": "Central African Republic",
    "CG": "Congo",
    "CH": "Switzerland",
    "CI": "Côte d'Ivoire",
    // "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    // "CW": "Curaçao",
    "CX": "Christmas Island",
    "CY": "Cyprus",
    "CZ": "Czechia",

    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",

    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    // "EH": "Western Sahara",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "EU": "European Union",

    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Islands", // "FK": "Falkland Islands (Malvinas)",
    "FM": "Federated States of Micronesia",
    "FO": "Faroe Islands",
    "FR": "France",

    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "Georgia",
    "GF": "French Guiana",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "Gambia",
    "GN": "Guinea",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    // "GS": "South Georgia and the South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",

    "HK": "Hong Kong",
    "HM": "Heard Island and McDonald Islands",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",

    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IM": "Isle of Man",
    "IN": "India",
    // "IO": "British Indian Ocean Territory",
    "IQ": "Iraq",
    "IR": "Iran", // "IR": "Islamic Republic of Iran",
    "IS": "Iceland",
    "IT": "Italy",

    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",

    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comoros",
    "KN": "Saint Kitts and Nevis",
    "KP": "North Korea", // "KP": "Democratic People's Republic of Korea",
    "KR": "South Korea", // "KR": "Republic of Korea",
    "KW": "Kuwait",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",

    "LA": "Laos", // "LA": "Lao People's Democratic Republic",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",

    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Moldova", // "MD": "Republic of Moldova",
    "ME": "Montenegro",
    "MF": "Saint Martin", // "MF": "Collectivity of Saint Martin",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MK": "Macedonia", // "MK": "Republic of Macedonia",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolia",
    "MO": "Macao",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",

    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "New Zealand",

    "OM": "Oman",

    "PA": "Panama",
    "PE": "Peru",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "Saint Pierre and Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PS": "Palestine, State of",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",

    "QA": "Qatar",

    "RE": "Réunion",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russian Federation",
    "RW": "Rwanda",

    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SH": "Saint Helena, Ascension and Tristan da Cunha",
    "SI": "Slovenia",
    "SJ": "Svalbard and Jan Mayen",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Suriname",
    "SS": "South Sudan",
    "ST": "Sao Tome and Principe",
    "SV": "El Salvador",
    // "SX": "Sint Maarten",
    "SY": "Syrian Arab Republic",
    "SZ": "Swaziland",

    "TC": "Turks and Caicos Islands",
    "TD": "Chad",
    // "TF": "French Southern Territories",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TK": "Tokelau",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TR": "Turkey",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan",
    "TZ": "United Republic of Tanzania", // "TZ": "Tanzania",

    "UA": "Ukraine",
    "UG": "Uganda",
    // "UM": "United States Minor Outlying Islands",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",

    "VA": "Vatican City",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela",
    "VG": "British Virgin Islands",
    "VI": "United States Virgin Islands",
    "VN": "Vietnam",
    "VU": "Vanuatu",

    // "WF": "Wallis and Futuna",
    "WS": "Samoa",

    "XK": "Kosovo", // "XK": "Republic of Kosovo",

    "YE": "Yemen",
    "YT": "Mayotte",

    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",

    /* no flag */
    "__": "NO_FLAG"
  },
  "interface": {
    "close": "Close",
    "copy": "Copy",
    "copied": "Copied",
    "help": "Help",
    "help1": "Copy and paste your markdown into the text box (or drag-and-drop).",
    "help2": "Click \"Find Flags\".",
    "help3": "Copy and paste the results into your markdown file.",
    "feedback": "Issues or Feedback",
    "example": "Example",
    "config": "Settings",
    "config-ignore": "Ignore errors",
    "config-name": "Set country name in title (hover text)",
    "config-code": "Set country code in alt (image failed to load text)",
    "config-inout": "Include input with output",
    "config-lang": "Output Lanauage:",
    "errors": "Errors",
    "parse": "Find Flags"
  },
  "example": "# Example Tournament XXYY\n\n![World Cup XXYY](logo.jpg)\n\nThe Example Tournament XXYY (*ET XXYY*) is not a real tournament because this is an example. It is the first and last installment for flag-wiki-osu.\n\n## Tournament schedule\n\nTo be announced.\n\n## Organisation\n\nThe Example Tournament XXYY is ran by various community members by distributing the multitude of tasks into various fields of responsibility.\n\n### Tournament management\n\n- ![][flag_DE] [Loctav](https://osu.ppy.sh/users/71366)\n- ![][flag_DE] [p3n](https://osu.ppy.sh/users/123703)\n- ![ES][flag_ES] [Deif](https://osu.ppy.sh/users/318565)\n- ![][flag_FR] [shARPII](https://osu.ppy.sh/users/776257)\n\n### Map selectors\n\n- ![][flag_JP] [Asahina Momoko](https://osu.ppy.sh/users/3650145)\n- ![][flag_DE] [Okorin](https://osu.ppy.sh/users/1623405)\n- ![][flag_HK] [Skystar](https://osu.ppy.sh/users/873961)\n\n### Commentators\n\n- ![][flag_AU] [Bauxe](https://osu.ppy.sh/users/1881685)\n- ![][flag_US] [Daikyi](https://osu.ppy.sh/users/811832)\n- ![][flag_NZ] [deadbeat](https://osu.ppy.sh/users/128370)\n- ![][flag_GB] [Doomsday](https://osu.ppy.sh/users/18983)\n- ![](/wiki/shared/flag/CA.gif) [Evrien](https://osu.ppy.sh/users/791660)\n- ![][flag_AR] [juankristal](https://osu.ppy.sh/users/443656)\n- ![](/wiki/shared/flag/AT.gif \"Austria\") [Omgforz](https://osu.ppy.sh/users/578943)\n- ![][flag_GB] [Rime](https://osu.ppy.sh/users/1397232)\n- ![][flag_FR] [Slainv](https://osu.ppy.sh/users/4823843)\n- ![][flag_US] [ztrot](https://osu.ppy.sh/users/6347)\n\n### Statistician\n\n- ![][flag_NZ] [deadbeat](https://osu.ppy.sh/users/128370)\n- ![][flag_DE] [Nwolf](https://osu.ppy.sh/users/1910766)\n"
});
