export default Object.freeze({
  "_version": 4,
  "_name": "French (output only)",
  "flag": {
    "__": "",

    "AD": "Andorre",
    "AE": "Émirats arabes unis",
    "AF": "Afghanistan",
    "AG": "Antigua-et-Barbuda",
    "AI": "Anguilla",
    "AL": "Albanie",
    "AM": "Arménie",
    "AN": "Antilles néerlandaises",
    "AO": "Angola",
    "AR": "Argentine",
    "AS": "Samoa américaines",
    "AT": "Autriche",
    "AU": "Australie",
    "AW": "Aruba",
    "AX": "Åland",
    "AZ": "Azerbaijan",

    "BA": "Bosnie-Herzégovine",
    "BB": "Barbade",
    "BD": "Bangladesh",
    "BE": "Belgique",
    "BF": "Burkina Faso",
    "BG": "Bulgarie",
    "BH": "Bahreïn",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint Barthelemy",
    "BM": "Bermudes",
    "BN": "Brunéi Darussalam",
    "BO": "Bolivie",
    "BR": "Brésil",
    "BS": "Bahamas",
    "BT": "Bhoutan",
    "BW": "Botswana",
    "BY": "Biélorussie",
    "BZ": "Belize",

    "CA": "Canada",
    "CD": "Congo, La République Démocratique du",
    "CF": "République centrafricaine",
    "CG": "Congo",
    "CH": "Suisse",
    "CI": "Cote D'Ivoire",
    "CL": "Chili",
    "CM": "Cameroun",
    "CN": "Chine",
    "CO": "Colombie",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cap-Vert",
    "CX": "Île Christmas",
    "CY": "Chypre",
    "CZ": "Tchéquie",

    "DE": "Allemagne",
    "DJ": "Djibouti",
    "DK": "Danemark",
    "DM": "Dominique",
    "DO": "République dominicaine",
    "DZ": "Algérie",

    "EC": "Equateur",
    "EE": "Estonie",
    "EG": "Egypte",
    "ER": "Érythrée",
    "ES": "Espagne",
    "ET": "Ethiopie",
    "EU": "Europe",

    "FI": "Finlande",
    "FJ": "Fiji",
    "FK": "Îles Falkland (Malvinas)",
    "FM": "Micronésie",
    "FO": "Îles Féroé",
    "FR": "France",

    "GA": "Gabon",
    "GB": "Royaume-Unis",
    "GD": "Grenada",
    "GE": "Géorgie",
    "GF": "Guyane française",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Groenland",
    "GM": "Gambie",
    "GN": "Guinée",
    "GP": "Guadeloupe",
    "GQ": "Guinée équatoriale",
    "GR": "Grèce",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinée-Bissau",
    "GY": "Guyane",

    "HK": "Hong Kong",
    "HM": "Îles Heard et McDonald",
    "HN": "Honduras",
    "HR": "Croatie",
    "HT": "Haiti",
    "HU": "Hongrie",

    "ID": "Indonésie",
    "IE": "Irlande",
    "IL": "Israel",
    "IM": "Île de Man",
    "IN": "Inde",
    "IQ": "Iraq",
    "IR": "Iran",
    "IS": "Islande",
    "IT": "Italie",

    "JE": "Jersey",
    "JM": "Jamaïque",
    "JO": "Jordanie",
    "JP": "Japon",

    "KE": "Kenya",
    "KG": "Kirghizistan",
    "KH": "Cambodge",
    "KI": "Kiribati",
    "KM": "Comores",
    "KN": "Saint-Kitts-et-Nevis",
    "KP": "Corée du Nord",
    "KR": "Corée du Sud",
    "KW": "Koweït",
    "KY": "Îles Caïmans",
    "KZ": "Kazakhstan",

    "LA": "Laos",
    "LB": "Liban",
    "LC": "Sainte-Lucie",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Libéria",
    "LS": "Lesotho",
    "LT": "Lituanie",
    "LU": "Luxembourg",
    "LV": "Lettonie",
    "LY": "Libie",

    "MA": "Maroc",
    "MC": "Monaco",
    "MD": "Moldavie",
    "ME": "Montenegro",
    "MF": "Sain-Martin",
    "MG": "Madagascar",
    "MH": "Îles Marshall",
    "MK": "Macédoine du Nord",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolie",
    "MO": "Macao",
    "MP": "Îles Mariannes du Nord",
    "MQ": "Martinique",
    "MR": "Mauritanie",
    "MS": "Montserrat",
    "MT": "Malte",
    "MU": "Maurice",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexique",
    "MY": "Malaisie",
    "MZ": "Mozambique",

    "NA": "Namibie",
    "NC": "Nouvelle Calédonie",
    "NE": "Niger",
    "NF": "Île Norfolk",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Pays-Bas",
    "NO": "Norvège",
    "NP": "Népal",
    "NR": "Nauru",
    "NU": "Niué",
    "NZ": "Nouvelle-Zélande",

    "OM": "Oman",

    "PA": "Panama",
    "PE": "Pérou",
    "PF": "Polynésie Française",
    "PG": "Papouasie-Nouvelle-Guinée",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Pologne",
    "PM": "Saint-Pierre-et-Miquelon",
    "PN": "Îles Pitcairn",
    "PR": "Porto Rico",
    "PS": "Territoires palestiniens occupés",
    "PT": "Portugal",
    "PW": "Palaos",
    "PY": "Paraguay",

    "QA": "Qatar",

    "RE": "Reunion",
    "RO": "Roumanie",
    "RS": "Serbie",
    "RU": "Russie",
    "RW": "Rwanda",

    "SA": "Arabie saoudite",
    "SB": "Îles Salomon",
    "SC": "Seychelles",
    "SD": "Soudan",
    "SE": "Suède",
    "SG": "Singapour",
    "SH": "Sainte-Hélène",
    "SI": "Slovénie",
    "SJ": "Svalbard et Jan Mayen",
    "SK": "Slovaquie",
    "SL": "Sierra Leone",
    "SM": "Saint-Marin",
    "SN": "Sénégal",
    "SO": "Somalie",
    "SR": "Suriname",
    "ST": "Sao Tomé-et-Principe",
    "SV": "El Salvador",
    "SY": "Syrie",
    "SZ": "Eswatini",

    "TC": "Îles Turks et Caïques",
    "TD": "Tchad",
    "TG": "Togo",
    "TH": "Thaïlande",
    "TJ": "Tajikistan",
    "TL": "Timor-Leste",
    "TM": "Turkménistan",
    "TN": "Tunisie",
    "TO": "Tonga",
    "TR": "Turquie",
    "TT": "Republique de Trinite et Tobago",
    "TV": "Tuvalu",
    "TW": "Taïwan",
    "TZ": "Tanzanie",

    "UA": "Ukraine",
    "UG": "Ouganda",
    "US": "États-Unis",
    "UY": "Uruguay",
    "UZ": "Ouzbékistan",

    "VA": "Vatican",
    "VC": "Saint-Vincent et les Grenadines",
    "VE": "Venezuela",
    "VG": "Îles Vierges britanniques",
    "VI": "Îles Vierges des États-Unis",
    "VN": "Vietnam",
    "VU": "Vanuatu",

    "WS": "Samoa",

    "YE": "Yémen",
    "YT": "Mayotte",

    "ZA": "Afrique du Sud",
    "ZM": "Zambie",
    "ZW": "Zimbabwe",
  },
});
